language: python

python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
  - "pypy3"

env:
  - TOXENV=py

# Test the nightly build of cpython, but ignore any failures.
# Add separate test environments for the docs and flake8 linter.
matrix:
  allow_failures:
    - python: "nightly"
  include:
    - env: TOXENV=docs
      python: 3.7
    - env: TOXENV=spelling
      python: 3.7
    - env: TOXENV=linter
      python: 3.8
    - env: TOXENV=pkglint
      python: 3.8

# Pull all of the history so we can use reno
git:
  depth: false

before_install:
  - sudo apt-get -y install libenchant1c2a

install:
  - pip install tox

script:
  - tox

deploy:
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
  provider: pypi
  user: __token__
  password:
    secure: "LcKMGh8rF8R4/yVYXPUpsyHseUxlYg3jF/Y76nfqhiKkS/5Vw2g6qgav2gHpjKEW4kJVzfCEfJ3FyCJgV50P9UcWvG6a8p+ld7rmEel7nXcfym6xFvxDJa+MGQmdU0NlelKAsPF+RRIG96WLoU/B53AqiypaSMZ1sjr1nFeisRvif7FwAJlgeimgWBxWuJx7UmJ5NblDaWKvA4YGb3fJWnuGxk8DKmLvrEnfzaVRE5HCkebk9dOfPWGUG4D7apUFPX1rgF2MC49aHYWXEG4lfzg4ldd6EtCNC1eY36MYK5rHjjmw1JTxHwwmpMXZ1QCwwuk7UFW+trkiuc43qtqxtlha7MSwCO6Q/8V9g/CvrUf+iOpy7yKsooD/VrWAIJql8Z3BfAXR23IJwtdEU8bwt0rCMu64+UAPXxlSITXEZAqOZnsKlLpF437VfG7clEGcguajPKMyvDKD/GMEx6vWhY3uEOvjVx+2rJ6sAq+joyX6qkwE0eYqgCcDJQhHYP3orJmednKeKnkGtSUC9g+amlPfDyoDrTyFwsCKbuCDgnSFm8G9o10CXii6IUQ0peVdbBCPdmZXjUNqQAcKgD9rL2qC3/Tp+QZZlIpLq1JVtmb9L0Svu3XSjwCVdhYuNm2mgeiFy3Hr/RSB+GFHEsOI/Eh9zV0qMy+ZjQ7yQ0A7Dow="
